server:
  port: 8089

spring:
  application:
    name: InstagramLab

  mvc:
    static-path-pattern: /uploads/**

  freemarker:
    expose-session-attributes: true

  datasource:
    url: jdbc:h2:./db/instagram_lab;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/master.yml

  mail:
    host: smtp.gmail.com
    username: res.pswd.attractor@gmail.com
    password: udbj mooa cwid osgt
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  web:
    resources:
      static-locations: file:./uploads/

logging:
  level:
    root: info
  file:
    path: logs